### ISSUE TITLE
Example fish1 not working with 5.0.1: had to prepend 'geofire' object

### ISSUE THREAD

**Issue by suztomo** [firebase/geofire-js#182]
Think you found a bug?
=======================
Yeah, we're definitely not perfect! Please use the bug report template below and include a minimal
repro when opening the issue.

### Version info

**Firebase:**
3.7.0

**GeoFire:**
5.0.1

**Other (e.g. Node, browser, operating system) (if applicable):**

Using GeoFire without NodeJS.

### Test case

Try to use this fish1 example with version 5.0.1
https://github.com/firebase/geofire-js/tree/master/examples/fish1

### Steps to reproduce

Try to use this fish1 example with version 5.0.1
https://github.com/firebase/geofire-js/tree/master/examples/fish1

```
  var geoFire = new GeoFire(firebaseRef);
```

### Expected behavior

GeoFire instance is created without an error.

### Actual behavior

You get an error 'ReferenceError: GeoFire is not defined'. GeoFire class is not found. 

### Workaround

Using `geofire` object worked:

```
  var geoFire = new geofire.GeoFire(firebaseRef);
```

**Comment by suztomo** [comment]
And when I tried Firebase 5.8.4, it gave an error "firebase.database is not a function". Adding following script resolved the issue.

```
<script src="https://www.gstatic.com/firebasejs/5.8.5/firebase-database.js"></script>
```

(Because Geofire uses Firestore database. 3.7.0 did not require explicit dependency to firestore database.)

**Comment by MichaelSolati** [comment]
I'll update the samples this week, hopefully we can get that merged in quickly.

**Comment by suztomo** [comment]
Thank you.
